FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .


RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy project
COPY app ./app

EXPOSE 8001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]